name: Publish
on:
  workflow_dispatch:
    inputs:
      version_type:
        type: choice
        options:
          - prerelease
          - prepatch
          - preminor
          - premajor
          - patch
          - minor
          - major
        required: true
      npm_tag:
        required: true
        type: choice
        options:
          - canary
          - latest
          - alpha
          - beta

jobs:
  publish:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
    steps:
      - run: 'git config --global user.email "github-actions[bot]"'
      - run: 'git config --global user.name "github-actions[bot]@users.noreply.github.com"'
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: "20"
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - if: github.event.inputs.npm_tag != 'latest'
        run: 'npm config set preid "${{ github.event.inputs.npm_tag }}"'
      - run: "npm version ${{ github.event.inputs.version_type }}"
      - uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
      - uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}
          tag: ${{ github.event.inputs.npm_tag }}
      - run: "bun install"
      - run: "bun add bunsai@${{ github.event.inputs.npm_tag }} && bun test"
        working-directory: "./tests"
